# Generated by Django 4.1.11 on 2023-09-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('base_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationmenuitem',
            options={},
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='navigationmenuitem',
            unique_together={('translation_key', 'locale')},
        ),
    ]
